### ISSUE TITLE
Lab_id has to be changed from physc01 to physc11

### ISSUE THREAD

**Issue by mrudhvika940** [vlabs-on-openedx/open-edx-optics-virtual-lab-amrita#2]
Lab.'s id has to be changed from physc01 to physc11  for the following labs. 
1) Angle of prism
2)  Spectrometer Determination of Cauchy's constants.
3) Spectrometer Dispersive power of a prism.

**Comment by sivashankerN** [comment]
Experiment "Spectrometer i-i Curve" has wrong lab_id "physc01".
fixed by giving lab_id "physc11"

**Comment by sivashankerN** [comment]
Experiment "Spectrometer Determination of Cauchy's constants" has wrong lab_id "physc01"
fixed by giving "physc11" as lab_id

**Comment by sravanthimodepu** [comment]
Closing the issue.
